spring:
  datasource:
    url: jdbc:mysql://129.154.192.255:3306/quant?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&profileSQL=true
    username: root
    password: 1q2w3e4r5t6Y!
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    connection-test-query: SELECT 1

aws:
  accessKey: accessKey
  secretKey: secretKey