version: "3"
services:
  report-assignment:
    image: mysql:latest
    container_name: hoon7566-mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - spring-network
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100
  report:
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://report-assignment:3306/hoon7566
    container_name: report
    image: openjdk:17-jdk-slim
    ports:
        - "8082:8080"
    volumes:
        - ./:/myapp
    working_dir: /myapp
    command: ["./gradlew", "bootrun"]
    depends_on:
        - report-assignment
    restart: always
    networks:
        - spring-network

networks:
  spring-network:
